version: "3.8"

services:
  php-apache:
    build: ./services/php-apache
    ports:
      - "80:80"
    volumes:
        - ./source:/var/www/html
        - ./services/php-apache/php.ini:/usr/local/etc/php/php.ini
        - ./services/php-apache/apache.conf:/etc/apache2/sites-available/000-default.conf
        - ./services/php-apache/logs/error.log:/var/log/apache2/error.log
    depends_on:
        - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./services/mysql/config:/etc/mysql/conf.d
      - ./services/mysql/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mysql
      - php-apache